ESE/urls.py
from django.urls import include, path, re_path
from . import views

urlpatterns = [
    path('students/', views.students_view, name='students'),
    path('profile/<int:pk>', views.student_detail, name='student_detail'),
    path('user/delete/<int:pk>', views.user_delete, name='user_delete'),
    path('modules/', views.modules_view, name='modules'),
    path('modules/add/', views.module_add, name='module_add'),
    path('modules/edit/<int:pk>', views.module_edit, name='module_edit'),
    path('modules/delete/<int:pk>', views.module_delete, name='module_delete'),
    path('modules/<int:pk>/competency/add/', views.competency_add, name='competency_add'),
    path('modules/<int:p_pk>/competency/delete/<int:pk>', views.competency_delete, name='competency_delete'),
    path('modules/competency/<int:pk>/edit/', views.competency_edit, name='competency_edit'),
    path('modules/competency/<int:pk>', views.competency_detail, name='competency_detail'),
    path('module/<int:pk>', views.module_detail, name='module_detail'),
    path('module/competency/<int:competency_id>/upload/', views.handle_file_upload, name='upload_file_view'),
    path('module/competency/<int:competency_id>/edit/<int:file_id>', views.handle_file_edit, name='upload_file_edit'),
    path('module/competency/<int:competency_id>/delete/<int:file_id>', views.handle_file_delete, name='upload_file_delete'),
    path('students/add/', views.user_add, name='user_add'),
    path('profile/edit/<int:pk>', views.user_edit, name='user_edit'),
    path('competency/<int:competency_id>/assessor/edit/', views.select_assessor, name='add_assessor'),
    path('competency/<int:competency_id>/assessor/confirm/<int:student_id>', views.confirm_select_assessor, name='confirm_assessor'),
    path('competency/<int:competency_id>/assessor/delete/<int:student_id>', views.confirm_delete_assessor, name='delete_assessor'),
    path('ajax/filter_competency/', views.filter_competencies_view, name='filter_views'),
    path('post/<int:pk>', views.post_single, name='post_single'),
    path('post/add/', views.post_add, name='post_add'),
    path('post/edit/<int:pk>', views.post_edit, name='post_edit'),
    path('post/delete/<int:pk>', views.post_delete, name='post_delete'),
    path('competency/<int:competency_id>/ratings/', views.rating_students, name='rating_students'),
    path('posts/', views.post_list, name='post_list'),
    re_path(r'^$', views.home_view, name='home'),
]

ePortfolio_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('ESE.urls')),
]
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ESE/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from datetime import datetime
from django import forms
from django.db.models.signals import post_save


RATING = (
    (0, 'Not Demostrated'), 
    (1, 'Weak'),
    (2, 'Strong'),
)


DAYS = (
    [(i, i) for i in range(1, 31)]
)

MONTHS = (
    (1, 'Jan'),
    (2, 'Feb'),
    (3, 'Mar'),
    (4, 'Apr'),
    (5, 'May'),
    (6, 'June'),
    (7, 'Jul'),
    (8, 'Aug'),
    (9, 'Sep'),
    (10, 'Oct'),
    (11, 'Nov'),
    (12, 'Dec'),
)

YEARS = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
    )

SEMESTER = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
    )

LEVELS = (
    ('Bachelor', 'Bachelor'),
    ('Master', 'Master'),
)


class Module(models.Model):
    name = models.CharField(max_length=150)
    summary = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    year = models.IntegerField(choices=YEARS, default=1)
    semester = models.IntegerField(choices=SEMESTER, default=1)
    level = models.CharField(max_length=100, choices=LEVELS, default='Bachelor')

    def __str__(self):
        return self.name


class Competency(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=600, null=True, blank=True)
    module = models.ManyToManyField(Module, related_name='competencies', blank=True)
    group_name = models.CharField(max_length=128)
    dimension_name = models.CharField(max_length=128)

    class Meta:
        verbose_name_plural = 'Competencies'

    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    picture = models.ImageField(null=True, blank=True, default='no-img.png')
    email = models.EmailField(max_length=100, null=True)
    major = models.CharField(max_length=100, null=True)
    country = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.CharField(max_length=100, null=True)
    module = models.ManyToManyField(Module, related_name='students', blank=True)
    assessor = models.ManyToManyField(Competency, related_name='assessor', blank=True)
    year = models.IntegerField(choices=YEARS, default=1)
    competency = models.ManyToManyField(Competency, related_name='competency', blank=True)
    semester = models.IntegerField(choices=SEMESTER, default=1)
    level = models.CharField(max_length=100, choices=LEVELS, default=1)

    def __str__(self):
        if self.first_name and not self.last_name:
            return self.first_name
        elif self.first_name and self.last_name:
            return self.first_name + ' ' + self.last_name
        else:
            return 'Student'


def create_profile(sender, **kwargs):
    if kwargs['created']:
        student = Student.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


class New(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    picture = models.ImageField(null=True, blank=True)
    create_date = models.DateTimeField(default=datetime.now)

    def get_content(self):
        return self.content[:150] + '...'

    def __str__(self):
        return self.title


class Rating(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, null=True)
    module = models.ForeignKey(Module, on_delete=models.CASCADE, blank=True, null=True)
    competency = models.ForeignKey(Competency, on_delete=models.CASCADE,blank=True, null=True)
    rating = models.IntegerField(choices=RATING, default=0)
    feedback = models.TextField(max_length=6000, null=True, blank=True)

    def __str__(self):
        return self.student.student.first_name + ' ' + self.student.student.last_name


class Upload(models.Model):
    name = models.CharField(max_length=100)
    competency = models.ForeignKey(Competency, on_delete=models.CASCADE)
    file = models.FileField(upload_to='files/', validators=[FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])])
    upload_time = models.DateTimeField(default=datetime.now, null=True)

    def get_extension_short(self):
        ext = str(self.file).split(".")
        ext = ext[len(ext)-1]

        if ext == 'doc' or ext == 'docx':
            return 'word'
        elif ext == 'pdf':
            return 'pdf'
        elif ext == 'xls' or ext == 'xlsx':
            return 'excel'
        elif ext == 'ppt' or ext == 'pptx':
            return 'powerpoint'
        elif ext == 'zip' or ext == 'rar' or ext == '7zip':
            return 'archive'

    def __str__(self):
        return str(self.file)[6:]



def get_full_name(self):
    if self.student.first_name and self.student.last_name:
        return self.student.first_name + ' ' + self.student.last_name
    return self.username

User.add_to_class("__str__", get_full_name)

ESE/forms.py
from django import forms
from .models import Upload, Student, New, Rating, Module, Competency
from django.contrib.auth.models import User
from django.forms import CharField

# Upload files to specific course
class UploadFormFile(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ('name', 'file', 'competency', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})


# Add/Edit User profile
class UpdateProfile(forms.ModelForm):

    # course = forms.ModelMultipleChoiceField(queryset=Course.objects.all(), widget=forms.CheckboxSelectMultiple)

    is_super = forms.BooleanField(required=False)

    class Meta:
        model = Student
        fields = ('first_name', 'last_name', 'email', 'module', 'country', 'city','picture', 'user','major', 'competency',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].widget.attrs.update({'hidden': True})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Last Name'})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Email'})
        self.fields['country'].widget.attrs.update({'class': 'form-control'})
        self.fields['city'].widget.attrs.update({'class': 'form-control', 'placeholder': 'City'})
        self.fields['module'].widget.attrs.update({'class': 'form-control'})
        self.fields['major'].widget.attrs.update({'class': 'form-control'})
        self.fields['competency'].widget.attrs.update({'class': 'full-width', 'required': False})


# Sign up form
class SignUpForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget = forms.PasswordInput())
    password2 = forms.CharField(widget = forms.PasswordInput())
    

    def clean_username(self):
        try:
            User.objects.get(username__iexact=self.username)
            raise forms.ValidationError('User already exists')
        except User.DoesNotExist:
            return self.username


    def clean_password(self):
        pw1 = self.cleaned_data.get('password1')
        pw2 = self.cleaned_data.get('password2')

        if pw1 and pw2 and pw1 == pw2:
            return pw1
        raise forms.ValidationError("Password doesn't match")


# Select teachers for a specific competency
class SelectAssessorsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('first_name', 'last_name', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'] = forms.ModelMultipleChoiceField(queryset=Student.objects.all())
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})


class AddPostForm(forms.ModelForm):
    class Meta:
        model = New
        fields = ('title', 'content', 'picture', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['content'].widget.attrs.update({'class': 'form-control'})
        self.fields['picture'].widget.attrs.update({'class': 'form-control'})


class RatingStudentsForm(forms.ModelForm):

    # student = forms.ChoiceField(choices=[(s.pk, s.first_name + ' ' + s.last_name) for s in Student.objects.all()])

    class Meta:
        model = Rating
        fields = ('student', 'rating', 'feedback',)

    def __init__(self, *args, **kwargs):
        super(RatingStudentsForm, self).__init__(*args, **kwargs)
        # if course:
            # self.fields['student'].widget = forms.ChoiceField(choices=[(s.pk, s.first_name) for s in Student.objects.all()])
        # self.fields['student'].widget = forms.ChoiceField(queryset=Student.objects.values_list('pk', 'first_name'))
        self.fields['student'].widget.attrs.update({'class': 'form-control'})
        self.fields['rating'].widget.attrs.update({'class': 'form-control'})
        self.fields['feedback'].widget.attrs.update({'class': 'form-control'})


class DateInput(forms.DateInput):
    input_type = 'date'


class CompetencyAddForm(forms.ModelForm):

    class Meta:
        model = Competency
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['module'].widget.attrs.update({'class': 'form-control'})
        self.fields['group_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['dimension_name'].widget.attrs.update({'class': 'form-control'})



class ModuleForm(forms.ModelForm):

    class Meta:
        model = Module
        fields = '__all__'
        widgets = {
            'start_date': DateInput(),
            'end_date': DateInput()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['summary'].widget.attrs.update({'class': 'form-control'})
        self.fields['level'].widget.attrs.update({'class': 'form-control'})
        self.fields['year'].widget.attrs.update({'class': 'form-control'})
        self.fields['semester'].widget.attrs.update({'class': 'form-control'})
        self.fields['start_date'].widget.attrs.update({'class': 'form-control'})
        self.fields['end_date'].widget.attrs.update({'class': 'form-control'})
        #self.fields['competencies'].widget.attrs.update({'class': 'form-control'})

ESE/templates/admin_panel.html
{% extends 'base_generic.html' %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="card-box">
                <h6>Afatet e Provimeve</h6>
                <small class="faded">Afatet per paraqitjen e provimeve</small>
                <hr>
                <!-- <br> -->
                <form method="post">
                    {% csrf_token %}
                    <table>
                        <thead>
                            <tr>
                                <th style="max-width: 40px">Aktiv</th>
                                <th>Emri</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                    {{ formset.management_form }} {% for form in formset %}
                            {{ form.id }}
                            <tr>
                                <td style="max-width: 40px" class="text-center">{{ form.aktiv }}</td>
                                <td>{{ form.emri }}</td>
                                <td class="text-center">{% if form.id.value %}<small><a class="text-danger" href="{% url 'delete_afat' pk=form.id.value %}">Fshije</a></small>{% endif %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if formset|length == 0 %}
                    <p class="lead">Asnje afat nuk u gjet</p>
                    {% endif %}
                    <br>
                    <a href="{% url 'administrator' afat_extra=extra|add:1 %}" class="float-right btn btn-primary">+</a>
                    <input type="submit" value="Ruaj ndryshimet" class="float-left btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ESE/templates/modules_list.html
{% extends 'base_generic.html' %} {% block content %}
<div class="container">
    <div class="shadow-box">
        {% if modules %}
        <table>
            <thead>
                <tr>
                    <th>Module name</th>
                    {% if user.is_superuser %}
                    <th></th>
                    {% endif %}
                </tr>
            </thead>
            {% for m in modules %}
            <tr>
                <td><a href="{% url 'module_detail' pk=m.pk %}">{{ m }}</a></td>
                {% if user.is_superuser %}
                <td class="text-right">
                    <a title="Edit" href="{% url 'module_edit' pk=m.pk %}" class="label sm-label"><i class="fas fa-pencil-alt"></i></a>
                    <span class="with-popup">
                        <div class="popup p-delete">
                            <p>Are you sure you want to remove this module?</p>
                            <a href="{% url 'module_delete' pk=m.pk %}">Remove</a>
                        </div>
                        <a title="Delete" class="label sm-label"><i class="fas fa-times"></i></a>
                    </span>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>There are no modules available</p>
        {% endif %}
    </div>
    {% if user.is_superuser %}
    <div class="empty-box">
        <a href="{% url 'module_add' %}" class="btn btn-primary">Add New Module</a>
    </div>
    {% endif %}
</div>
{% endblock %}

ESE/templates/student_profile.html
{% extends 'base_generic.html' %}


{% block content %}

{% if user.is_superuser or user.student == student %}
<div class="abs-popup">
    <div class="no-shade card-box grades">
        <!-- <h5>Success</h5><br/> -->
        <a onclick="toggleRatings()" class="toggleBtn btn btn-danger"><i class="fas fa-times"></i> Close</a><br><br>
        <table>
            <thead>
                <th>Competency</th>
                <th>Rating</th>
                <small class="faded">(Please double click the buttons.)</small>
            </thead>
            <tbody>
                {% if success %}
                {% for rating in success %}
                <tr>
                    <td>{{ rating.competency }}</td>
                    <td>{% if rating.rating >= 0 %}{{ rating.rating }}{% else %}&mdash;{% endif %}</td>
                    <td><a onclick="toggleFeedbacks()" class="toggleBtn btn btn-primary">view the comments</a></td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td>Empty dataset</td>
                    <td></td>
                </tr>
                {% endif %}
            </tbody>
        </table><br>
    </div>
</div>
{% endif %}


<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="no-shade card-box">
                <div class="row">
                    <div class="col-md-3 col-xs-12 text-center">
                        <div class="thumb img-round">
                            <img src="../static/uploads/{% if student.picture %}{{ student.picture }} {% else %}no-img.png {% endif %}" />
                        </div>
                        {% if user.is_authenticated %}
                        {% if user.student.pk == student.pk or user.is_superuser %}
                        <div class="text-left">
                            <br/>
                            <a class="btn btn-primary" style="display: block" href="{% url 'user_edit' pk=student.pk %}"><i class="material-icons">edit</i>Edit</a><br/>
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>
                    <div class="col-md-9 col-xs-12">
                        <h3>{{ student.first_name }} {{ student.last_name }}</h3>
                        <small class="faded lead">
                            {{ student.get_level_display }} &mdash; {{ student.major }}</a>
                        </small>
                        <hr/>
                        <div><span class="sm-label label text-primary"><i class="fas fa-map-marker"></i></span> {{ student.city }}, {{ student.country }}</div><br/>
                        <div><span class="sm-label label text-primary"><i class="fas fa-envelope"></i></span> {{ student.email }}</div>
                        
                        <hr/>
                        <h5>Enrolled Modules</h5>
                        {% if student.module.all %}
                            {% if student.module.all|length > 8 %}
                            <div class="hide">
                                <div class="white-shadow">
                                    <div onclick="showModules(this)" id="trigger">Expand <i class="fas fa-angle-down"></i></div>
                                </div>
                            {% endif %}
                                {% for module in student.module.all %}
                                <a class="label" href="{% url 'module_detail' pk=module.pk %}" title="{{ module.summary }}">{{ module }}</a>
                                {% endfor %}
                            {% if student.module.all|length > 8 %}
                            </div>
                            {% endif %}
                            {% else %}
                        <b class="text-danger">No modules</b>
                        {% endif %}
                        <h5>Competency Ratings</h5>
                        {% if student.competency.all %}
                            {% if student.competency.all|length > 8 %}
                            <div class="hide">
                                <div class="white-shadow">
                                    <div onclick="showCompetencies(this)" id="trigger">Expand <i class="fas fa-angle-down"></i></div>
                                </div>
                            {% endif %}
                                {% for competency in student.competency.all %}
                                <a class="label" href="{% url 'competency_detail' pk=competency.pk %}" title="{{ competency.description }}">{{ competency }}</a>
                                {% endfor %}
                            {% if student.competency.all|length > 8 %}
                            </div>
                            {% endif %}
                            {% else %}
                        <b class="text-danger">No competencies</b>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if user.is_superuser or user.student == student %}
            <div class="empty-box text-left">
                <a onclick="toggleRatings()" class="toggleBtn btn btn-primary">view the ratings</a>
            </div>
            {% endif %}
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="card-box">
                <h6>Overview</h6>
                <small class="faded">0 = 'Not Demontrated'; 1 = 'Weak'; 2 = 'Strong'.</small>
                <table>
                    <tbody>
                        <tr>
                            <td>The Sum of Rating</td>
                            <td>{{ details.rating__sum|floatformat:0 }}</td>
                        </tr>
                        <tr>
                            <td>Highest Rating</td>
                            <td>{% if not details.rating__max %}&mdash;{% else %}{{ details.rating__max }}{% endif %}</td>
                        </tr>
                        <tr>
                            <td>Lowest Rating</td>
                            <td>{% if not details.rating__min %}&mdash;{% else %}{{ details.rating__min }}{% endif %}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% if user.is_superuser or user.student == student %}
<div class="com-popup" style="visibility:hidden" id="popUp">
        <div class="no-shade card-box grades" >
            <a onclick="toggleFeedbacks()" class="toggleBtn btn btn-danger"><i class="fas fa-times"></i> Close</a><br><br>
            <table>
                <thead>
                    <th>Comments</th>
                </thead>
                <tbody>
                    {% if success %}
                    {% for rating in success %}
                    <tr>
                        <td>{{ rating.feedback }}</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td>Empty dataset</td>
                        <td></td>
                    </tr>
                    {% endif %}
                </tbody>
            </table><br>
        </div>
    </div>
{% endif %}
{% endblock %}


{% block javascript %}
<script>
    var visible = false;
    var collapsed = true;
    
    function toggleRatings() {
        if (visible) {
            $('.abs-popup').hide()
        } else {
            $('.abs-popup').show();
            $('.abs-popup').css('display', 'flex');
        }
        visible = !visible;
    }

    function toggleFeedbacks() {
        if (visible) {
            popUp.style.visibility = "hidden";
        } else {
            popUp.style.visibility = "visible";
        }
        visible = !visible;
    }

    function showCompetencies(btn) {
        var btn = $(btn);
        if (collapsed) {
            btn.html("Collapse <i class=\"fas fa-angle-up\"></i>");
            $(".hide").css("max-height", "unset");
            $(".white-shadow").css({"background": "unset", "z-index": "0"});
        } else {
            btn.html("Expand <i class=\"fas fa-angle-down\"></i>");
            $(".hide").css("max-height", "150");
            $(".white-shadow").css({"background": "linear-gradient(transparent 50%, rgba(255,255,255,.8) 80%)", "z-index": "2"});
        }
        collapsed = !collapsed;
    }
</script>
{% endblock %}

ESE/templates/upload_file_form.html
{% extends 'base_generic.html' %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-xs-12">
            <form method="post" enctype="multipart/form-data" >
                <div class="card-box">
                    {% csrf_token %}
                    <h6>Upload file</h6>
                    <div class="form-group">
                        File name<br/>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        {{ form.file }}
                    </div>
                    <div class="form-group">
                        <select hidden name="competency" required="" id="id_competency">
                            <option value="{{ competency.pk }}" selected>{{ competency }}</option>
                        </select>
                    </div>
                </div>
                <div class="empty-box">
                    <button type="submit" class="btn btn-primary">Upload</button>
                    <a class="btn btn-danger" href="{% url 'competency_detail' pk=competency.pk %}">Cancel</a>
                </div>
                <hr>
                <small class="faded">Valid files: <b>PDF, Word, Excel, Powepoint, Zip/Rar</b></small>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ESE/templates/user_profile_edit.html
{% extends 'base_generic.html' %}


{% block javascript %}
{% load static %}
<script src="{% static 'js/ajax.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <div class="card-box">
                        <h6>Personal info</h6><br/>
                        {% csrf_token %}
                        {{ form.user }}
                        <div class="form-group">
                            {{ form.first_name }}
                        </div>
                        <div class="form-group">
                            {{ form.last_name }}
                        </div>
                        <div class="form-group">
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="card-box">
                        <h6>Other</h6><br/>
                        <div class="form-group">
                            {{ form.picture }}
                        </div>
                                             
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card-box">
                        <h6>Location</h6><br/>
                        <div class="form-group">
                            {{ form.country }}
                        </div>
                        <div class="form-group">
                            {{ form.city }}
                        </div>
                    </div>
                    <div class="card-box">
                        <h6>Major Info</h6><br/>
                        <div class="form-group">
                            {{ form.major }}
                        </div>
                    
                        <div class="form-group position-relative">
                            <div class="form-group">
                                <h6>Module info</h6>
                                {{ form.module }}<br/>
                            </div>
                            {{ form.competency }}<br/>
                            <small class="faded">Hold 'Control', or 'Command' on Mac and select</small>
                        </div>
                    </div>
                    {% if user.is_superuser %}
                    <div class="no-shade card-box">
                        <div class="form-check">
                            {{ form.is_super }} 
                            <label class="form-check-label" for="id_is_super">
                                Superuser
                            </label>
                        </div>
                    </div>
                    {% endif %}
                    <!-- <div class="col-md-6"> -->
                    <div class="empty-box">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a class="btn btn-danger" href="{% url 'student_detail' pk=student.pk %}">Back</a>
                    </div>
                <!-- </div> -->
                </div>
            </div>
        </form>
</div>
{% endblock %}